### ISSUE TITLE
want-data is partly dynamic and has to be adapated to got before equality-check

### ISSUE THREAD

**Issue by fabstu** [hexops/autogold#14]
I have want-data for which part of got is dynamic.

My example is this. This is the want-data:

```yaml
    - root:
        items:
        - download:
            ilias: Algos 2
            name: Algos1
            options:
              download_folder: ""
        path: 02-ss2021
    path: %s
```

I read this data, do `want := fmt.Sprintf(wantRaw, path)` and then compare with `assert.Equal`:

```yaml
    - root:
        items:
        - download:
            ilias: Algos 2
            name: Algos1
            options:
              download_folder: ""
        path: 02-ss2021
    path: /var/folders/rw/35q09zqj5yv5pz4wwg3yjfkm0000gn/T/TestSetup_basic278973801/001
```

I can't see how to do this with `autogold.Equal` at the moment. Any ideas? I guess generics would be an easy solution but that's still a long time out. :-)
